/*
 * Sterilisation API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.41
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';
import {NewTray} from './NewTray';

/**
 * The NewOrder model module.
 * @module model/NewOrder
 * @version 1.0
 */
export class NewOrder {
  /**
   * Constructs a new <code>NewOrder</code>.
   * @alias module:model/NewOrder
   * @class
   * @param customerId {Number} 
   * @param trays {Array.<module:model/NewTray>} 
   */
  constructor(customerId, trays) {
    this.customerId = customerId;
    this.trays = trays;
  }

  /**
   * Constructs a <code>NewOrder</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/NewOrder} obj Optional instance to populate.
   * @return {module:model/NewOrder} The populated <code>NewOrder</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new NewOrder();
      if (data.hasOwnProperty('customerId'))
        obj.customerId = ApiClient.convertToType(data['customerId'], 'Number');
      if (data.hasOwnProperty('trays'))
        obj.trays = ApiClient.convertToType(data['trays'], [NewTray]);
    }
    return obj;
  }
}

/**
 * @member {Number} customerId
 */
NewOrder.prototype.customerId = undefined;

/**
 * @member {Array.<module:model/NewTray>} trays
 */
NewOrder.prototype.trays = undefined;

