/*
 * Sterilisation API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.41
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';
import {Operation} from './Operation';

/**
 * The NewTray model module.
 * @module model/NewTray
 * @version 1.0
 */
export class NewTray {
  /**
   * Constructs a new <code>NewTray</code>.
   * @alias module:model/NewTray
   * @class
   * @param id {Number} 
   * @param trayTypeId {Number} 
   * @param trayTypeName {String} 
   * @param operation {module:model/Operation} 
   */
  constructor(id, trayTypeId, trayTypeName, operation) {
    this.id = id;
    this.trayTypeId = trayTypeId;
    this.trayTypeName = trayTypeName;
    this.operation = operation;
  }

  /**
   * Constructs a <code>NewTray</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/NewTray} obj Optional instance to populate.
   * @return {module:model/NewTray} The populated <code>NewTray</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new NewTray();
      if (data.hasOwnProperty('id'))
        obj.id = ApiClient.convertToType(data['id'], 'Number');
      if (data.hasOwnProperty('trayTypeId'))
        obj.trayTypeId = ApiClient.convertToType(data['trayTypeId'], 'Number');
      if (data.hasOwnProperty('trayTypeName'))
        obj.trayTypeName = ApiClient.convertToType(data['trayTypeName'], 'String');
      if (data.hasOwnProperty('operation'))
        obj.operation = Operation.constructFromObject(data['operation']);
    }
    return obj;
  }
}

/**
 * @member {Number} id
 */
NewTray.prototype.id = undefined;

/**
 * @member {Number} trayTypeId
 */
NewTray.prototype.trayTypeId = undefined;

/**
 * @member {String} trayTypeName
 */
NewTray.prototype.trayTypeName = undefined;

/**
 * @member {module:model/Operation} operation
 */
NewTray.prototype.operation = undefined;

