/*
 * Sterilisation API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.41
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';

/**
 * The Operation model module.
 * @module model/Operation
 * @version 1.0
 */
export class Operation {
  /**
   * Constructs a new <code>Operation</code>.
   * @alias module:model/Operation
   * @class
   * @param id {Number} 
   * @param _date {Date} 
   * @param doctor {String} 
   */
  constructor(id, _date, doctor) {
    this.id = id;
    this._date = _date;
    this.doctor = doctor;
  }

  /**
   * Constructs a <code>Operation</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/Operation} obj Optional instance to populate.
   * @return {module:model/Operation} The populated <code>Operation</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new Operation();
      if (data.hasOwnProperty('id'))
        obj.id = ApiClient.convertToType(data['id'], 'Number');
      if (data.hasOwnProperty('date'))
        obj._date = ApiClient.convertToType(data['date'], 'Date');
      if (data.hasOwnProperty('doctor'))
        obj.doctor = ApiClient.convertToType(data['doctor'], 'String');
    }
    return obj;
  }
}

/**
 * @member {Number} id
 */
Operation.prototype.id = undefined;

/**
 * @member {Date} _date
 */
Operation.prototype._date = undefined;

/**
 * @member {String} doctor
 */
Operation.prototype.doctor = undefined;

