/*
 * Sterilisation API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.41
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';

/**
 * The SterilisationProcess model module.
 * @module model/SterilisationProcess
 * @version 1.0
 */
export class SterilisationProcess {
  /**
   * Constructs a new <code>SterilisationProcess</code>.
   * @alias module:model/SterilisationProcess
   * @class
   * @param name {String} 
   * @param staffId {Number} 
   * @param finished {Boolean} 
   */
  constructor(name, staffId, finished) {
    this.name = name;
    this.staffId = staffId;
    this.finished = finished;
  }

  /**
   * Constructs a <code>SterilisationProcess</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/SterilisationProcess} obj Optional instance to populate.
   * @return {module:model/SterilisationProcess} The populated <code>SterilisationProcess</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new SterilisationProcess();
      if (data.hasOwnProperty('name'))
        obj.name = ApiClient.convertToType(data['name'], 'String');
      if (data.hasOwnProperty('staffId'))
        obj.staffId = ApiClient.convertToType(data['staffId'], 'Number');
      if (data.hasOwnProperty('date'))
        obj._date = ApiClient.convertToType(data['date'], 'Date');
      if (data.hasOwnProperty('finished'))
        obj.finished = ApiClient.convertToType(data['finished'], 'Boolean');
    }
    return obj;
  }
}

/**
 * @member {String} name
 */
SterilisationProcess.prototype.name = undefined;

/**
 * @member {Number} staffId
 */
SterilisationProcess.prototype.staffId = undefined;

/**
 * @member {Date} _date
 */
SterilisationProcess.prototype._date = undefined;

/**
 * @member {Boolean} finished
 */
SterilisationProcess.prototype.finished = undefined;

